DemirbasTakipOtomasyonu/Controllers/DemirbasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DemirbasTakipOtomasyonu.Models;
using Rotativa;

namespace DemirbasTakipOtomasyonu.Controllers
{
    public class DemirbasController : Controller
    {
        private OtomasyonEntities db = new OtomasyonEntities();

        // GET: Demirbas
        //[Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            var demirbas = db.Demirbas.Include(d => d.DemirbasTuru).Include(d => d.Departman).Include(d => d.Fakulte);
            if (User.IsInRole("admin"))
            {
                return View(demirbas.ToList());
            }  
            else if(User.IsInRole("yetkili"))
            {
                return View("Hata");
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
            
        }

        public ActionResult PrintStock()
        {
            var model = db.Demirbas;
            ViewAsPdf pdf = new ViewAsPdf("Index", model);
            return pdf;
        }

        // GET: Demirbas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Demirbas demirbas = db.Demirbas.Find(id);
            if (demirbas == null)
            {
                return HttpNotFound();
            }
            return View(demirbas);
        }

        // GET: Demirbas/Create
        //[Authorize(Roles ="admin")]
        public ActionResult Create()
        {
            ViewBag.DemirbasTurId = new SelectList(db.DemirbasTuru, "Id", "Ad");
            //ViewBag.FakulteId = new SelectList(db.Fakulte, "Id", "Ad");
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad");

            /*var roles =*//* User.IsInRole("admin");*/
            if (User.IsInRole("admin"))
            {
                return View();
            }
            else if(User.IsInRole("yetkili"))
            {
                return View("Hata");
            }
            else
            {
                return RedirectToAction("Login","Account");
            }
        }

        // POST: Demirbas/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Ad,Fiyat,AlımTarihi,Adet,DemirbasTurId,FakulteId,DepartmanId")] Demirbas demirbas)
        {
            if (ModelState.IsValid)
            {
                Departman departman = new Departman();
                departman = db.Departman.Find(demirbas.DepartmanId);
                demirbas.FakulteId = departman.FakulteId;
                demirbas.AlımTarihi = DateTime.Now;
                db.Demirbas.Add(demirbas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DemirbasTurId = new SelectList(db.DemirbasTuru, "Id", "Ad", demirbas.DemirbasTurId);
            //ViewBag.FakulteId = new SelectList(db.Fakulte, "Id", "Ad", demirbas.FakulteId);
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad", demirbas.DepartmanId);
            return View(demirbas);
        }

        // GET: Demirbas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Demirbas demirbas = db.Demirbas.Find(id);
            if (demirbas == null)
            {
                return HttpNotFound();
            }
            ViewBag.DemirbasTurId = new SelectList(db.DemirbasTuru, "Id", "Ad", demirbas.DemirbasTurId);
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad", demirbas.DepartmanId);
            ViewBag.FakulteId = new SelectList(db.Fakulte, "Id", "Ad", demirbas.FakulteId);
            return View(demirbas);
        }

        // POST: Demirbas/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Ad,Fiyat,AlımTarihi,Adet,DemirbasTurId,FakulteId,DepartmanId")] Demirbas demirbas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(demirbas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DemirbasTurId = new SelectList(db.DemirbasTuru, "Id", "Ad", demirbas.DemirbasTurId);
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad", demirbas.DepartmanId);
            ViewBag.FakulteId = new SelectList(db.Fakulte, "Id", "Ad", demirbas.FakulteId);
            return View(demirbas);
        }

        // GET: Demirbas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Demirbas demirbas = db.Demirbas.Find(id);
            if (demirbas == null)
            {
                return HttpNotFound();
            }
            return View(demirbas);
        }

        // POST: Demirbas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Demirbas demirbas = db.Demirbas.Find(id);
            db.Demirbas.Remove(demirbas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DemirbasTakipOtomasyonu/Controllers/OdaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemirbasTakipOtomasyonu.Models;

namespace DemirbasTakipOtomasyonu.Controllers
{
    public class OdaController : Controller
    {
        private OtomasyonEntities db = new OtomasyonEntities();

        // GET: Oda
        [Authorize(Roles = "admin,yetkili")]
        public ActionResult Index(int? id)
        {
            var oda = db.Oda.Include(o => o.Departman).Include(o => o.Personel).AsQueryable();

            if(id!=null)
            {
                oda = oda.Where(i => i.PersonelId == id);
            }
            return View(oda.ToList());
        }

        // GET: Oda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oda oda = db.Oda.Find(id);
            if (oda == null)
            {
                return HttpNotFound();
            }
            return View(oda);
        }

        // GET: Oda/Create
        //[Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad");
            ViewBag.PersonelId = new SelectList(db.Personel, "Id", "Ad");

            if (User.IsInRole("admin"))
            {
                return View();
            }
            else if (User.IsInRole("yetkili"))
            {
                return View("Hata");
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: Oda/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Ad,DepartmanId,PersonelId")] Oda oda)
        {
            if (ModelState.IsValid)
            {
                db.Oda.Add(oda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad", oda.DepartmanId);
            ViewBag.PersonelId = new SelectList(db.Personel, "Id", "Ad", oda.PersonelId);
            return View(oda);
        }

        // GET: Oda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oda oda = db.Oda.Find(id);
            if (oda == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad", oda.DepartmanId);
            ViewBag.PersonelId = new SelectList(db.Personel, "Id", "Ad", oda.PersonelId);
            return View(oda);
        }

        // POST: Oda/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Ad,DepartmanId,PersonelId")] Oda oda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad", oda.DepartmanId);
            ViewBag.PersonelId = new SelectList(db.Personel, "Id", "Ad", oda.PersonelId);
            return View(oda);
        }

        // GET: Oda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (User.IsInRole("admin"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Oda oda = db.Oda.Find(id);
                if (oda == null)
                {
                    return HttpNotFound();
                }
                return View(oda);
            }
            else if (User.IsInRole("yetkili"))
            {
                return View("Hata");
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: Oda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Oda oda = db.Oda.Find(id);
            db.Oda.Remove(oda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DemirbasTakipOtomasyonu/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemirbasTakipOtomasyonu.Models;

namespace DemirbasTakipOtomasyonu.Controllers
{
    public class PersonelController : Controller
    {
        private OtomasyonEntities db = new OtomasyonEntities();
        
        // GET: Personel
        [Authorize(Roles = "admin,yetkili")]
        public ActionResult Index()
        { 

            return View(db.Personel.ToList());
            
        }

        // GET: Personel/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //db.Oda.Where(i => i.PersonelId == id).Select(i => i.Ad);

            //Personel personel = db.Personel.Find(id);
            //if (personel == null)
            //{
            //    return HttpNotFound();
            //}
            return View(db.Oda.Where(i => i.PersonelId == id).Select(i => i.Ad));
        }

        // GET: Personel/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Personel/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Ad,Soyad")] Personel personel)
        {
            if (ModelState.IsValid)
            {
                db.Personel.Add(personel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(personel);
        }

        // GET: Personel/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personel personel = db.Personel.Find(id);
            if (personel == null)
            {
                return HttpNotFound();
            }
            return View(personel);
        }

        // POST: Personel/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Ad,Soyad")] Personel personel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(personel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(personel);
        }

        // GET: Personel/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personel personel = db.Personel.Find(id);
            if (personel == null)
            {
                return HttpNotFound();
            }
            return View(personel);
        }

        // POST: Personel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Personel personel = db.Personel.Find(id);
            db.Personel.Remove(personel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DemirbasTakipOtomasyonu/Views/Shared/Hata.cshtml
@{
    ViewBag.Title = "Hata";
}

<div class="alert alert-danger" role="alert">Bu işlemi yapmak için yetkiniz yoktur!</div>

<div class="col-md-12">
    <img height="300" width="300" src="https://vignette.wikia.nocookie.net/gtawiki/images/9/96/Lock.png/revision/latest?cb=20141101143614" />
</div>

DemirbasTakipOtomasyonu/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        * {
            box-sizing: border-box;
        }

        #myInput {
            background-image: url('/css/searchicon.png');
            background-position: 10px 10px;
            background-repeat: no-repeat;
            width: 100%;
            font-size: 16px;
            padding: 12px 20px 12px 40px;
            border: 1px solid #ddd;
            margin-bottom: 12px;
        }

        /*#myTable {
            border-collapse: collapse;
            width: 100%;
            /*border: 1px solid #ddd;*/
            font-size: 18px;
        }

            #myTable th, #myTable td {
                text-align: left;
                padding: 12px;
            }

            #myTable tr {
                border-bottom: 1px solid #ddd;
            }

                #myTable tr.header, #myTable tr:hover {
                    background-color: #f1f1f1;
                }*/
    </style>
    <script>
        function myFunction() {
            var input, filter, table, tr, td, i;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Demirbaş Takip Otomasyonu", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Odalar", "Index", "Oda")</li>
                    <li>@Html.ActionLink("Demirbaş Ata", "Create", "OdaDemirbasAtama")</li>
                    <li>@Html.ActionLink("Personeller", "Index", "Personel")</li>
                    <li>@Html.ActionLink("Demirbaş Stok", "Index", "Demirbas")</li>
                    <li>@Html.ActionLink("Demirbaş Kayıt", "Create", "Demirbas")</li>
                    @*<li>
                            @using (Html.BeginForm("Index", "Personel", FormMethod.Get))
                            {
                            <form class="navbar-form navbar-right" role="search" action="~/Controllers/Personel/Index" method="get">
                                <div class="form-group">
                                    @Html.TextBox("q", null, new { @class = "form-control" })
                                </div>
                                <button type="submit" class="btn btn-default">Ara</button>
                            </form>
                            }
                        </li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
       
            @RenderBody()
            <br />
            <br />
            <br />
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Demirbaş Takip Otomasyon Sistemi</p>
            </footer>    
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>