DemirbasTakipOtomasyonu/Models/Oda.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasTakipOtomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oda()
        {
            this.OdaDemirbasAtama = new HashSet<OdaDemirbasAtama>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public int DepartmanId { get; set; }
        public int PersonelId { get; set; }
    
        public virtual Departman Departman { get; set; }
        public virtual Personel Personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdaDemirbasAtama> OdaDemirbasAtama { get; set; }
    }
}

DemirbasTakipOtomasyonu/Controllers/OdaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemirbasTakipOtomasyonu.Models;

namespace DemirbasTakipOtomasyonu.Controllers
{
    public class OdaController : Controller
    {
        private OtomasyonEntities db = new OtomasyonEntities();

        // GET: Oda
        [Authorize(Roles = "admin,yetkili")]
        public ActionResult Index(int? id)
        {
            var oda = db.Oda.Include(o => o.Departman).Include(o => o.Personel).AsQueryable();

            if(id!=null)
            {
                oda = oda.Where(i => i.PersonelId == id);
            }
            return View(oda.ToList());
        }

        // GET: Oda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oda oda = db.Oda.Find(id);
            if (oda == null)
            {
                return HttpNotFound();
            }
            return View(oda);
        }

        // GET: Oda/Create
        //[Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad");
            ViewBag.PersonelId = new SelectList(db.Personel, "Id", "Ad");

            if (User.IsInRole("admin"))
            {
                return View();
            }
            else if (User.IsInRole("yetkili"))
            {
                return View("Hata");
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: Oda/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Ad,DepartmanId,PersonelId")] Oda oda)
        {
            if (ModelState.IsValid)
            {
                db.Oda.Add(oda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad", oda.DepartmanId);
            ViewBag.PersonelId = new SelectList(db.Personel, "Id", "Ad", oda.PersonelId);
            return View(oda);
        }

        // GET: Oda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oda oda = db.Oda.Find(id);
            if (oda == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad", oda.DepartmanId);
            ViewBag.PersonelId = new SelectList(db.Personel, "Id", "Ad", oda.PersonelId);
            return View(oda);
        }

        // POST: Oda/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Ad,DepartmanId,PersonelId")] Oda oda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmanId = new SelectList(db.Departman, "Id", "Ad", oda.DepartmanId);
            ViewBag.PersonelId = new SelectList(db.Personel, "Id", "Ad", oda.PersonelId);
            return View(oda);
        }

        // GET: Oda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (User.IsInRole("admin"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Oda oda = db.Oda.Find(id);
                if (oda == null)
                {
                    return HttpNotFound();
                }
                return View(oda);
            }
            else if (User.IsInRole("yetkili"))
            {
                return View("Hata");
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: Oda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Oda oda = db.Oda.Find(id);
            db.Oda.Remove(oda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DemirbasTakipOtomasyonu/Controllers/OdaDemirbasAtamaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DemirbasTakipOtomasyonu.Models;
using Rotativa;

namespace DemirbasTakipOtomasyonu.Controllers
{
    public class OdaDemirbasAtamaController : Controller
    {
        private OtomasyonEntities db = new OtomasyonEntities();
        

        // GET: OdaDemirbasAtama
        [Authorize(Roles = "admin,yetkili")]
        public ActionResult Index(int? id)
        {
            var odaDemirbasAtama = db.OdaDemirbasAtama.Include(o => o.Demirbas).Include(o => o.Oda).AsQueryable();
            if (id != null)
            {
                odaDemirbasAtama = odaDemirbasAtama.Where(i => i.OdaId == id);
            }
            return View(odaDemirbasAtama.ToList());
        }

        public ActionResult PrintAllReport(int? id)
        {
           
            var  model = db.OdaDemirbasAtama.Where(i => i.OdaId == id);      
            ViewAsPdf pdf = new ViewAsPdf("Index", model);
            return pdf;

        }

        public ActionResult Print()
        {
            var model = db.OdaDemirbasAtama;
            ViewAsPdf pdf = new ViewAsPdf("Index", model);
            return pdf;
        }

        // GET: OdaDemirbasAtama/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OdaDemirbasAtama odaDemirbasAtama = db.OdaDemirbasAtama.Find(id);
            if (odaDemirbasAtama == null)
            {
                return HttpNotFound();
            }
            return View(odaDemirbasAtama);
        }

        // GET: OdaDemirbasAtama/Create
        public ActionResult Create()
        {
            ViewBag.DemirbasId = new SelectList(db.Demirbas, "Id", "Ad");
            ViewBag.OdaId = new SelectList(db.Oda, "Id", "Ad");
            
            if (User.IsInRole("admin"))
            {
                return View();
            }
            else if (User.IsInRole("yetkili"))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        // POST: OdaDemirbasAtama/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,OdaId,DemirbasId,AtananAdet")] OdaDemirbasAtama odaDemirbasAtama)
        {
            Demirbas demirbas = new Demirbas();
            demirbas = db.Demirbas.Find(odaDemirbasAtama.DemirbasId);
            if (odaDemirbasAtama.AtananAdet > demirbas.Adet)
            {
                TempData["Stok"] = "Girdiğiniz değer stoktaki değerden fazladır.";
                return RedirectToAction("Create");
            }

            else if (odaDemirbasAtama.AtananAdet <= demirbas.Adet)
            {
                //demirbas.Adet = demirbas.Adet - odaDemirbasAtama.AtananAdet;
                //return RedirectToAction("Create");           

                //if (ModelState.IsValid)
                //{
                    demirbas.Adet = demirbas.Adet - odaDemirbasAtama.AtananAdet;
                    db.OdaDemirbasAtama.Add(odaDemirbasAtama);
                    db.SaveChanges();
                    return RedirectToAction("Index");
             }

                ViewBag.DemirbasId = new SelectList(db.Demirbas, "Id", "Ad", odaDemirbasAtama.DemirbasId);
                ViewBag.OdaId = new SelectList(db.Oda, "Id", "Ad", odaDemirbasAtama.OdaId);
                return View(odaDemirbasAtama);
            }
        

        // GET: OdaDemirbasAtama/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OdaDemirbasAtama odaDemirbasAtama = db.OdaDemirbasAtama.Find(id);
            //var adet1 = odaDemirbasAtama.AtananAdet;
            //TempData["adet"] = adet1;
            //Demirbas demirbas = new Demirbas();
            //demirbas = db.Demirbas.Find(odaDemirbasAtama.DemirbasId);
            //TempData["fark"] = 0;
            //if(odaDemirbasAtama.AtananAdet < demirbas.Adet)
            //{
            //    TempData["fark"] = demirbas.Adet - odaDemirbasAtama.AtananAdet;
            //}
            //else if(odaDemirbasAtama.AtananAdet > demirbas.Adet)
            //{
            //    TempData["fark"] = odaDemirbasAtama.AtananAdet - demirbas.Adet;
            //}

            if (odaDemirbasAtama == null)
            {
                return HttpNotFound();
            }
            ViewBag.DemirbasId = new SelectList(db.Demirbas, "Id", "Ad", odaDemirbasAtama.DemirbasId);
            ViewBag.OdaId = new SelectList(db.Oda, "Id", "Ad", odaDemirbasAtama.OdaId);
            return View(odaDemirbasAtama);
        }

        // POST: OdaDemirbasAtama/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OdaId,DemirbasId,AtananAdet")] OdaDemirbasAtama odaDemirbasAtama)
        {
            Demirbas demirbas = new Demirbas();
            demirbas = db.Demirbas.Find(odaDemirbasAtama.DemirbasId); //Demirbaşın stoktaki adeti
            //var adet2 = odaDemirbasAtama.AtananAdet;
            //var adet = TempData["adet"]
            if (ModelState.IsValid)
            {
                db.Entry(odaDemirbasAtama).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DemirbasId = new SelectList(db.Demirbas, "Id", "Ad", odaDemirbasAtama.DemirbasId);
            ViewBag.OdaId = new SelectList(db.Oda, "Id", "Ad", odaDemirbasAtama.OdaId);
            return View(odaDemirbasAtama);
        }

        // GET: OdaDemirbasAtama/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OdaDemirbasAtama odaDemirbasAtama = db.OdaDemirbasAtama.Find(id);
            if (odaDemirbasAtama == null)
            {
                return HttpNotFound();
            }

            //if (User.IsInRole("admin"))
            //{
            //    return View();
            //}
            //else if (User.IsInRole("yetkili"))
            //{
            //    return View("Hata");
            //}
            //else
            //{
            //    return RedirectToAction("Login", "Account");
            //}

            return View(odaDemirbasAtama);
        }

        // POST: OdaDemirbasAtama/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OdaDemirbasAtama odaDemirbasAtama = db.OdaDemirbasAtama.Find(id);
            Demirbas demirbas = new Demirbas();
            demirbas = db.Demirbas.Find(odaDemirbasAtama.DemirbasId);
            db.OdaDemirbasAtama.Remove(odaDemirbasAtama);
            demirbas.Adet += odaDemirbasAtama.AtananAdet;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DemirbasTakipOtomasyonu/Views/Oda/Create.cshtml
@model DemirbasTakipOtomasyonu.Models.Oda

@{
    ViewBag.Title = "Create";
}

<h2>Oda Tanımlama Sayfası</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ad,  new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Ad, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmanId, "Departman", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmanId", null,  new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmanId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonelId, "Personel", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonelId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Oda Listesine Dön", "Index",null,new { @class="btn btn-success"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemirbasTakipOtomasyonu/Views/Oda/Delete.cshtml
@model DemirbasTakipOtomasyonu.Models.Oda

@{
    ViewBag.Title = "Delete";
}

<h2>Silme İşlemi</h2>

<h3>Silmek istediğinizden emin misiniz?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departman.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departman.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personel.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personel.Ad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Geri Dön", "Index")
        </div>
    }
</div>

DemirbasTakipOtomasyonu/Views/Oda/Details.cshtml
@model DemirbasTakipOtomasyonu.Models.Oda

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Oda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departman.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Departman.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personel.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personel.Ad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DemirbasTakipOtomasyonu/Views/Oda/Edit.cshtml
@model DemirbasTakipOtomasyonu.Models.Oda

@{
    ViewBag.Title = "Edit";
}

<h2>Oda Güncelleme Sayfası</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Ad, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Ad, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmanId, "Departman", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmanId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmanId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonelId, "Personel", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonelId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Oda Listesine Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DemirbasTakipOtomasyonu/Views/Oda/Index.cshtml
@model IEnumerable<DemirbasTakipOtomasyonu.Models.Oda>

@{
    ViewBag.Title = "Index";
}

<h2>Odalar</h2>

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Filtrele" title="Type in a name">

<table class="table" id="myTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Departman.Ad)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Personel.Ad)*@
            Oda Sorumlusu
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="/OdaDemirbasAtama/Index/@item.Id">@item.Ad</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departman.Ad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Personel.Ad)
            </td>
            <td>
                @Html.ActionLink("Güncelle", "Edit", new { id = item.Id }, new { @class = "btn btn-success" })
                @Html.ActionLink("Odayı Sil", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                @Html.ActionLink("Rapor Al", "PrintAllReport","OdaDemirbasAtama", new { id = item.Id }, new { @class = "btn btn-success" })
            </td>
        </tr>
    }
</table>
<hr />
<p>
    @Html.ActionLink("Oda Tanımla", "Create", null, new { @class = "btn btn-success" })
</p>